* YouTube Playlist Downloader and Zotero RDF Generator

Download YouTube playlists and generate Zotero RDF XML files.

** Setup

1. Clone it:
   #+begin_src sh
     git clone https://github.com/dlawisch/yt-dlp-rdf
     cd yt-dlp-rdf
   #+end_src

2. Set up a virtual environment:
   #+begin_src sh
     python -m venv venv
     source venv/bin/activate   # On Windows, `venv\Scripts\activate`
   #+end_src

3. Install dependencies:
   #+begin_src sh
   pip install -r requirements.txt
   #+end_src

** Usage

Put your playlist URLs in `playlists.txt`, one per line.

*** Download and Generate RDF

Default mode: downloads and generates RDF for all playlists:
   #+begin_src sh
   python main.py playlists.txt --download-path path/to/download
   #+end_src

*** Download Only

Just download, no RDF:
   #+begin_src sh
   python main.py playlists.txt --download-only --download-path path/to/download
   #+end_src

*** RDF Only

Generate RDF for already downloaded playlists:
   #+begin_src sh
   python main.py playlists.txt --rdf-only --download-path path/to/download
   #+end_src

*** Verbose Mode

For detailed logging:
   #+begin_src sh
   python main.py playlists.txt --verbose --download-path path/to/download
   #+end_src

** CLI Flags

- playlists_file: Path to the file containing playlist URLs.
- --download-only: Only download the playlists without generating RDF files.
- --rdf-only: Only generate RDF files for already downloaded playlists.
- --download-path`: Path to the download directory. Defaults to `downloads`.
- --verbose: Enable detailed logging.* YouTube Playlist Downloader and Zotero RDF Generator
